package model;
// Generated May 14, 2015 6:29:41 PM by Hibernate Tools 4.3.1



/**
 * Donations generated by hbm2java
 */
public class Donations  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String phone;
     private Float latitude;
     private Float longitude;
     private String time;
     private String notes;

    public Donations() {
    }

    public Donations(String name, String phone, Float latitude, Float longitude, String time, String notes) {
       this.name = name;
       this.phone = phone;
       this.latitude = latitude;
       this.longitude = longitude;
       this.time = time;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


