package model;
// Generated May 14, 2015 6:29:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Logs generated by hbm2java
 */
public class Logs  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String phone;
     private Float latitude;
     private Float longitude;
     private Double weight;
     private String time;
     private String status;
     private String notes;

    public Logs() {
    }

    public Logs(String name, String phone, Float latitude, Float longitude, Double weight, String time, String status, String notes) {
       this.name = name;
       this.phone = phone;
       this.latitude = latitude;
       this.longitude = longitude;
       this.weight = weight;
       this.time = time;
       this.status = status;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


